GET:
  simple/$day: exampleHandler
  schemas/$schema/archives/$year/$month/$day: exampleHandler
  $day/classes/go: exampleHandler
  testing/hello/world: exampleHandler
  really/deep/example/of/a/static/uri/hello/dennis: exampleHandler
  really/$day/example/of/$month/static/uri/hello/dennis/$year: exampleHandler

params:
  year:   IsYear
  month:  IsMonth
  day:    IsDay